@startuml
class ParentClass{
    int field1
    {static} char field2
    {abstract} void methodA()
    double methodB()
}
class ChildClass{
    void methodA()
    {static} void methodC()
}
ParentClass <|-- ChildClass : extends
note as n1 
    staticなメソッドまたはフィールドは下線、
    abstractは斜線で表現される
end note
n1 .. ParentClass
@enduml